### ISSUE TITLE
Enhancement - Changes need in Orange Cat Cycles

### ISSUE THREAD

**Issue by roshan-ponnachen02** [RohitKV1n0d/orange_cat_web#167]
## Description
Changes need in Orange Cat Cycles

## Environment
https://orangecatcycles.com

### Issues

 **Issue 1**

- **Social Media page is not open up while click on the icon**

![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/654121f4-da18-4e97-b31c-b61af3938922)

**Issue 2**

- **Remove the feedback content**

![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/9d790463-c1db-487a-8b7b-d7e5ae45e48d)

**Issue 3**

- **Add template or caption if the order is empty on My Orders**

![Screenshot 2024-05-09 142422](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/b4f98c14-51bc-4a5b-9cbe-138057773e74)

**Issue 4**

- **Product price should be display like this.**

![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/0c04afbd-ce17-43b3-bc89-b549964d0a15)

**Comment by RohitKV1n0d** [comment]
@swathikrishnaus Please look into this.

**Comment by RohitKV1n0d** [comment]
- Also @swathikrishnaus , i have made some changes to the product price display, the update is that now only in the product details page the price will be shown, i have removed the price display from landing and models page. please check and see if any changes is required.
- ![Screenshot 2024-05-09 at 2 09 57 PM](https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/5b1456f6-3bb5-4fd8-944c-299f59af25cd)
- @swathikrishnaus please make this price in the product details page look like this.

**Comment by swathikrishnaus** [comment]
@roshan-ponnachen02 , For issue 1, we don't have social media links for Follow us section,  that's why we just keep it empty now

**Comment by roshan-ponnachen02** [comment]
@swathikrishnaus 

##Issue 3

The empty order template shows only when the user  not place an order

![Image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/0b2fac23-d866-4153-8fb1-0d47ac603d8d)
