### ISSUE TITLE
Issue 1 - User Created successfully without providing details , Issue 2 - User can login after update details on profile.

### ISSUE THREAD

**Issue by roshan-ponnachen02** [RohitKV1n0d/orange_cat_web#176]
## Description
Issue 1 - User Created successfully without providing details ,
Issue 2 - User can login after update details on profile.

## Environment
https://orangecatcycles.com/user/login

##Issue 1

## Steps to Reproduce
1. Click on the `Create an account`
2. Click on the `Register an account`

## Expected Behaviour
- Details are mandatory to create an account

## Actual Behaviour
- Showing User Created successfully

##Issue 2

## Steps to Reproduce
1. After created an account without entering details, click on Profile Icon
2. Enter details on the profile page and click on save
3. Click on `Profile` icon and Click on `Sign out`
4. In the log in Page , Enter Username only and click on `Login`

## Expected Behaviour
- Page is not allowed without providing details while create an account

## Actual Behaviour
- Successfully Login

## Screencast

https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/81135b09-84af-4de8-9fba-60560e1bc872

**Comment by RohitKV1n0d** [comment]
@roshan-ponnachen02 is this the correct video ?

**Comment by roshan-ponnachen02** [comment]
@RohitKV1n0d 

##Issue 1

- `Issue exist while create an account`
-  User is created without providing first and last



https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/ba55b884-41e4-44c4-b1f0-776e6fc43326

**Comment by RohitKV1n0d** [comment]
@roshan-ponnachen02 Fixed
